### ISSUE TITLE
Reference other tables from an item

### ISSUE THREAD

**Issue by ptaranat** [script-wizards/oracle#2]
We want the ability to chain tables. Should force lowercase.

```yaml
tables:
  Event:
    - "You find a pack. Inside, you find [items]."
  Items:
    - "{1d8}gp"
    - "a candle"
```
